AI_CHAT_HISTORY_EXTRACTION_PROMPT = """The candidate has provided a structured 13-section behavioral profile generated by another AI assistant (Claude, ChatGPT, etc.) based on their past conversations.

Convert this into a list of structured claims for use in our matching system. Each section becomes 1-3 claims.

For each claim:
- evidence_tier should almost always be "inferred" (chat history cannot verify hard facts). Use "stated" only when the candidate clearly self-described something concrete.
- source_excerpt should be a short paraphrase of the relevant section (NOT a verbatim quote — paraphrase to break identifying language).
- confidence should reflect how clearly the AI's output supported the claim (specific patterns = higher, generic statements = lower).
- tags should map to the section number and broad category (e.g. ["section_3", "working_style"], ["section_7", "communication"]).

DO NOT extract claims from sections marked "not enough signal", "no signal", "insufficient data", or any equivalent. Skip them entirely.

DO NOT extract any identifying information that may have leaked through despite the original prompt's privacy rules. Strip these before writing source_excerpts:
- Specific company names (employers, schools, organizations)
- Specific project names
- Specific framework or product names that identify a stack
- People's names (collaborators, managers)
- Locations more specific than country
- Dates more specific than year

If a section is entirely about identifying material once the above is stripped, skip it.

DO NOT extract claims about sensitive personal content (mental health, family, relationships, religion, politics). If a section mentions these, skip it even if the AI's output included them.

Output JSON with this exact structure:

{
  "summary": "2-3 sentences summarizing the behavioral profile as a whole (also stripped of identifiers)",
  "claims": [
    {
      "claim_text": "specific behavioral or motivational assertion",
      "evidence_tier": "inferred" | "stated",
      "source_excerpt": "short paraphrase (NOT verbatim) of the relevant section",
      "confidence": 0.0 to 1.0,
      "tags": ["section_N", "category"]
    }
  ]
}

(source_type is implicitly "ai_chat_history" — it will be added by the system, you do not need to emit it.)

Output ONLY valid JSON. No markdown fences."""
